/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedlist;

public class App {

    public static void main(String[] args) {

//      System.out.println("---------------------------------");
//      linkedlistStructure list =new linkedlistStructure();
//      System.out.println(list.to_string());
//      System.out.println("--------------------------");
//      list.insert("3");
//      list.insert("5");
//      list.insert("1");
//      list.insert("9");
//      System.out.println(list.to_string());
//      System.out.println( list.includes("3"));
//      list.append("10");
//      System.out.println(list.to_string());
//      list.insert_before("5","15");
//      System.out.println(list.to_string());
//      list.insert_after("5","16");
//      System.out.println(list.to_string());
//
//      list.linked_list_kth(6);
//      System.out.println(list.linked_list_kth(2));
//      System.out.println("-------------------------------------------------------------------------");
//      linkedlistStructure list2 =new linkedlistStructure();
//      list2.insert("8");
//      list2.insert("5");
//      list2.insert("6");
//      list2.insert("2");
//      System.out.println(list.to_string());
//      System.out.println(list2.to_string());
//
//      list.linked_list_zip(list,list2);
//      System.out.println("after zipping");
////      System.out.println(list.to_string());
//      Test test= new Test();
//
//      test.insert("3");
//      test.insert("1");

      linkedlistStructure link= new linkedlistStructure();
      link.append("2");
      link.append("1");
      link.append("3");
      link.append("5");
      link.append("6");
      link.append("4");
      link.append("7");
      System.out.println(link.to_string());
      linkedlistStructure x=link.Test();
      System.out.println(x.to_string());



    }
}
